// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwXHR5095UJtAmDB267tvg6PMvMeYXAzs',
    appId: '1:1043304535721:web:dba35205fc8ded51673bb8',
    messagingSenderId: '1043304535721',
    projectId: 'judo-exam',
    authDomain: 'judo-exam.firebaseapp.com',
    storageBucket: 'judo-exam.firebasestorage.app',
    measurementId: 'G-VRFWG4HYFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5T5bRLTQUAzpTRcFy5yitZRHQoSE0_r8',
    appId: '1:1043304535721:android:f554ed69bd51a5d5673bb8',
    messagingSenderId: '1043304535721',
    projectId: 'judo-exam',
    storageBucket: 'judo-exam.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyIeOGsKlZ-WoML69AjYaL7u8NphRXZ4E',
    appId: '1:1043304535721:ios:8391cfca9c2af850673bb8',
    messagingSenderId: '1043304535721',
    projectId: 'judo-exam',
    storageBucket: 'judo-exam.firebasestorage.app',
    iosClientId: '1043304535721-8m8p13tqshbr2qg0p20hg94gegoak288.apps.googleusercontent.com',
    iosBundleId: 'com.example.judoExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyIeOGsKlZ-WoML69AjYaL7u8NphRXZ4E',
    appId: '1:1043304535721:ios:8391cfca9c2af850673bb8',
    messagingSenderId: '1043304535721',
    projectId: 'judo-exam',
    storageBucket: 'judo-exam.firebasestorage.app',
    iosClientId: '1043304535721-8m8p13tqshbr2qg0p20hg94gegoak288.apps.googleusercontent.com',
    iosBundleId: 'com.example.judoExam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwXHR5095UJtAmDB267tvg6PMvMeYXAzs',
    appId: '1:1043304535721:web:12b8c7cd7c824b85673bb8',
    messagingSenderId: '1043304535721',
    projectId: 'judo-exam',
    authDomain: 'judo-exam.firebaseapp.com',
    storageBucket: 'judo-exam.firebasestorage.app',
    measurementId: 'G-GC3RRP4GEM',
  );
}
